[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
board_build.partitions = huge_app.csv
lib_deps =
    olikraus/U8g2@^2.35.19